keys:
  - &nixos-mother age13lxjuuxtacsa84zuxjlgy48a7ppv5695gaqjtwdh696ywnssqccquel5g9

creation_rules:
  - path_regex: .[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nixos-mother
